---

# Descarga e instalación de Elastic

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Instala la clave de Elastic
      apt-key: keyserver=keyserver.ubuntu.com id=D88E42B4


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Configuracion del repositorio de Elastic
      become: true
      command: echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Instalar suporte para apt con https
      become: true
      apt:
        name: apt-transport-https

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Actualiza los repositorios
      become: true
      apt:
        update_cache: yes

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Instalación de Elasticsearch
      become: true
      apt:
        name: elasticsearch

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Moverse a la carpeta /etc/elasticsearch para editar el archivo elasticsearch.yml
      become: true
      command: chdir=/etc/elasticsearch

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Moverse a la carpeta /etc/elasticsearch para editar el archivo elasticsearch.yml
      become: true
      blockinfile:- name: Insert multiple lines and Backup
  blockinfile:
    path: /etc/ssh/sshd_config
    backup: yes
    block: |
      network.host: 127.0.0.1
      script.inline: true
      cluster.name: hive
      thread_pool.index.queue_size: 100000
      thread_pool.search.queue_size: 100000
      thread_pool.bulk.queue_size: 100000

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Reinicia los daemon para ejecutar el servicio de elasticsearch
      become: true
      systemd:
        state: restarted
        daemon_reload: yes


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Habilita e inicia el servicio de elasticsearch
      become: true
      systemd:
        name: elasticsearch
        enable: yes
        state: start


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Verifica que el servicio de elasticsearch este funcionando
      become: true
      systemd: state=started name=elasticsearch


###############################################################################
# Descarga e instalación de THEHIVE

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Descarga TheHive
      become: true
      command: echo 'deb https://dl.bintray.com/thehive-project/debian-stable any main' | sudo tee -a /etc/apt/sources.list.d/thehive-project.list

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Descarga la clave
      become: true
      shell: curl https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY | sudo apt-key add -
      args:
        warn: no


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Actualiza los repositorios
      become: true
      apt:
        update_cache: yes


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Instala Cortex
      become: true
      apt:
        name: thehive


#El único parámetro requerido para iniciar TheHive es la clave del servidor (play.http.secret.key).
#Esta clave se usa para autenticar cookies que contienen datos. Si TheHive se ejecuta en modo de clúster,
#todas las instancias deben compartir la misma clave.
#Puede generar la configuración mínima con los siguientes comandos
#(suponen que se ha creado un usuario dedicado para TheHive, llamado thehive)

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Crea la carpeta thehive en /etc/thehive
      become: true
      file:
        path: /etc/thehive
        state: directory

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Descarga la clave
      become: true
      shell: (cat << _EOF_ # Secret key # ~~~~~
              # The secret key is used to secure cryptographics functions.
              # If you deploy your application to several instances be sure to use the same key!
              play.http.secret.key="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"
              _EOF_
              ) | sudo tee -a /etc/thehive/application.conf

      args:
        warn: no

#Se inicia el servicio de thehive

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Reinicia los daemon para ejecutar el servicio de thehive
      become: true
      systemd:
        state: restarted
        daemon_reload: yes


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Habilita e inicia el servicio de thehive
      become: true
      systemd:
        name: thehive
        enable: yes
        state: start


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Verifica que el servicio de thehive este funcionando
      become: true
      systemd: state=started name=thehive

#Ante cualquier problema, consultar la guia de instalacion de TheHive y Cortex
# https://gitlab.unc.edu.ar/csirt/thehive
# Donde se detallan posibles problemas y sus respectivas soluciones


#Instalación de Cortex

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Descarga Cortex
      become: true
      command: echo 'deb https://dl.bintray.com/thehive-project/debian-stable any main' | sudo tee -a /etc/apt/sources.list.d/thehive-project.list


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Descarga la clave
      become: true
      shell: curl https://raw.githubusercontent.com/TheHive-Project/Cortex/master/PGP-PUBLIC-KEY | sudo apt-key add -
      args:
        warn: no


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Actualiza los repositorios
      become: true
      apt:
        update_cache: yes


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Instala Cortex
      become: true
      apt:
        name: cortex


#Instalación de Analyzers y Responders

#Instalacion de dependencias previas

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Instala el conjunto de dependencias necesarias para los Analyzers y Responders
      apt: name={{item}} state=installed
      with_items:
       - python-pip
       - python2.7-dev
       - python3-pip
       - python3-dev
       - ssdeep
       - libfuzzy-dev
       - libfuzzy2
       - libimage-exiftool-perl
       - libmagic1
       - build-essential
       - git
       - libssl-dev

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Instala setuptools con pip
    - pip:
        name: setuptools

- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Instala setuptools con pip3
    - pip:
        name: setuptools
        executable: pip-3.3


- hosts: TheHive/Cortex
  remote_user: root
  tasks:
    - name: Clona el repositorio de analizadores de Cortex en el directorio /opt
    - git:
        repo: https://github.com/TheHive-Project/Cortex-Analyzers
        dest: /opt/


...
