---

- name: Instala el conjunto de dependencias necesarias para los Analyzers y Responders
  become: yes
  become_user: root
  apt: 
   pkg:
     - python-pip
     - python2.7-dev
     - python3-pip
     - python3-dev
     - ssdeep
     - libfuzzy-dev
     - libfuzzy2
     - libimage-exiftool-perl
     - libmagic1
     - build-essential
     - git
     - libssl-dev
   update_cache: yes

- name: Instala setuptools con pip
  become: yes
  become_user: root
  pip:
    name: setuptools

- name: Instala setuptools con pip3
  become: yes
  become_user: root
  pip:
    name: setuptools
    executable: pip3

- name: Clona el repositorio de Analyzers y Responders de Cortex en el directorio "{{path_default_analyzers }}"
  become: yes
  become_user: root
  git:
    repo: https://github.com/TheHive-Project/Cortex-Analyzers
    dest: "{{path_default_analyzers }}"


- name: Recursively find requirements.txt files in "{{path_default_analyzers }}"
  become: yes
  become_user: root
  find:
    paths: "{{path_default_analyzers }}"
    patterns: 'requirements.txt'
    recurse: yes
  register: requirements_paths

#- debug:
#    msg: "{{item.path}}"
#  with_items: "{{ requirements_paths.files }}"

#for I in $(find Cortex-Analyzers -name 'requirements.txt'); do sudo -H pip2 install -r $I; done && \
#for I in $(find Cortex-Analyzers -name 'requirements.txt'); do sudo -H pip3 install -r $I || true; done

# Install specified python requirements.
- name: Install specified python pip requirements for analyzers in "{{path_default_analyzers }}"
  become: yes
  become_user: root
  pip:
    requirements: "{{item.path}}"
  with_items: "{{ requirements_paths.files }}"

  # Install specified python requirements.
- name: Install specified python pip3 requirements for analyzers in "{{path_default_analyzers }}"
  become: yes
  become_user: root
  pip:
    requirements: "{{item.path}}"
    executable: pip3
  with_items: "{{ requirements_paths.files }}"