---

- name: Add TheHive repo
  become: yes
  become_user: root
  lineinfile:
    path: /etc/apt/sources.list.d/thehive-project.list
    line: deb https://dl.bintray.com/thehive-project/debian-stable any main
    create: yes


- name: Instala curl
  become: yes
  become_user: root
  apt:
    name: curl

- name: Add an apt key by id from a keyserver
  become: yes
  become_user: root
#  shell: curl https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY | sudo apt-key add -
#  args:
#    executable: /bin/bash
  apt_key: 
    url: https://raw.githubusercontent.com/TheHive-Project/TheHive/master/PGP-PUBLIC-KEY
    state: present

- name: Actualizar repo
  become: yes
  become_user: root
  apt:
   update_cache: yes

- name: Instalar TheHive
  become: yes
  become_user: root
  apt:
   name: thehive
   update_cache: yes

- name: Crea la carpeta thehive en /etc/thehive si no existe
  become: true
  become_user: root
  file:
    path: /etc/thehive
    state: directory
    mode: 0775

- name: Crear clave play.http.secret.key
  become: true
  become_user: root
  shell: cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1
  register: playhttpsecretkey

- name: Insertar clave play.http.secret.key en /etc/thehive/application.conf
  become: true
  become_user: root
  blockinfile:
    path: /etc/thehive/application.conf
    insertafter: EOF
    block: |
      # Secret key
      # ~~~~~
      # The secret key is used to secure cryptographics functions.
      # If you deploy your application to several instances be sure to use the same key!
      play.http.secret.key="{{playhttpsecretkey.stdout}}"

# https://github.com/TheHive-Project/TheHive/issues/757
- name: Insertar ' akka.remote.netty.tcp.hostname = "127.0.0.1" '' in /etc/thehive/application.conf
  become: true
  become_user: root
  lineinfile:
    path: /etc/thehive/application.conf
    insertafter: EOF
    line: akka.remote.netty.tcp.hostname = "127.0.0.1"


- name: Reinicia los daemon para ejecutar el servicio de TheHive
  become: true
  systemd:
   daemon_reload: yes

- name: Habilita e inicializa el servicio de TheHive
  become: yes
  become_user: root
  systemd:
    name: thehive.service
    state: started
    enabled: yes

- name: Make sure a service thehive.service is running
  systemd:
    state: started
    name: thehive.service

- name: Instalar python-pip
  become: yes
  become_user: root
  apt:
   name: python-pip
   update_cache: yes

- name: Instalar python3-pip
  become: yes
  become_user: root
  apt:
   name: python3-pip
   update_cache: yes

- name: Install thehive4py 
  pip:
    name: thehive4py


#depues de esto entrar a localhost:9000 y actualizar base de datos
#crear usuario administrador
#ir a la parte superior derecha admin - users
# create API key
# reveal 
#copiar se usara para cortex
