
#agregar a sudo visudo al final
#soniontest ALL=(ALL) ALL

---

- name: Install The Hive and Cortex
  hosts: all
#  become: yes
  gather_facts: yes

  roles:
#   - cortex_install
#    - download_default_analyzers_responders
#    - cortex_analyzers
    - cortex_responders

