---

- name: Install The Hive and Cortex
  hosts: all
#  become: yes
  gather_facts: yes

  roles:
  # - java_install
  # - elastic_install
  # - cortex_install
  # - download_default_analyzers_responders
   - cortex_analyzers
   - cortex_responders

