
#agregar a sudo visudo al final
#soniontest ALL=(ALL) ALL

---

- name: Install The Hive and Cortex
  hosts: all
#  become: yes
  gather_facts: yes

  roles:
#    - cortex_install
    - cortex_analyzers
#    - cortex_conf

